name: Live Media Forwarder Cloud Pipeline

on:
  workflow_dispatch:

jobs:
  run-bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Launch Prebuilt Live Container
        env:
          TOKEN: ${{ secrets.TOKEN }}
          READING_CHANNELS: ${{ secrets.SOURCE_SERVER }}
          WEBHOOKS: ${{ secrets.WEBHOOKS }}
        run: |
          docker run -d \
            -e TOKEN="$TOKEN" \
            -e READING_CHANNELS="$READING_CHANNELS" \
            -e WEBHOOKS="$WEBHOOKS" \
            --name cloud-forwarder \
            viossat/discord-forwarder
          
          echo "Container started successfully."
          sleep 5
          docker logs cloud-forwarder
