name: Live Media Forwarder Cloud Pipeline

on:
  workflow_dispatch:

jobs:
  run-bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Core Repository Assets
        uses: actions/checkout@v4

      - name: Boot Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Create JSON Configuration File
        run: |
          echo '{
            "TOKEN": "${{ secrets.TOKEN }}",
            "READING_CHANNELS": "${{ secrets.SOURCE_SERVER }}",
            "WEBHOOKS": "${{ secrets.WEBHOOKS }}"
          }' > config.json

      - name: Deploy Live Mirror Process
        run: |
          npm install
          npm start
